name: sign_experiment
data:
    data_path: /home/radumicea/Projects/University/LinguSign/new_feb_stuff/dataset
    vocab_file: /home/radumicea/Projects/University/LinguSign/new_feb_stuff/dataset/spm_unigram_lowercase_16k.vocab
    feature_size: 1024
    phoneme_dim: 38
    fps: 12.5
    max_sgn_len: 256
    max_txt_len: 128
    split_seed: 42
    multimodal: 0.0
testing:
    translation_beam_sizes:
    - 1
    - 2
    - 4
    - 6
    - 8
    - 10
    translation_beam_alphas:
    - -1
    - 0.0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
    - 1.0
training:
    reset_best_ckpt: false
    reset_scheduler: false
    reset_optimizer: false
    random_seed: 42
    model_dir: "./sign_sample"
    translation_loss_weight: 1.0
    eval_metric: bleu
    optimizer: adamw
    learning_rate: 0.001
    batch_size: 100
    num_valid_log: 50
    epochs: 1000
    early_stopping_metric: eval_metric
    translation_normalization: batch
    eval_translation_beam_size: 4
    eval_translation_beam_alpha: 0.6
    overwrite: true
    shuffle: true
    use_cuda: true
    translation_max_output_length: 128
    batch_multiplier: 1
    logging_freq: 400
    betas:
    - 0.95
    - 0.998
    scheduling: plateau
    learning_rate_min: 1.0e-06
    weight_decay: 0.003
    patience: 10
    decrease_factor: 0.8
    label_smoothing: 0.1
    lr_s_dim_model : 256
    warmup_step : 60000
    K: 2
model:
    initializer: xavier
    bias_initializer: zeros
    init_gain: 1.0
    embed_initializer: xavier
    embed_init_gain: 1.0
    tied_softmax: true
    cope: false
    encoder:
        type: transformer
        num_layers: 1
        num_heads: 8
        embeddings:
            embedding_dim: 256
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 256
        ff_size: 1024
        dropout: 0.1
    decoder:
        type: transformer
        num_layers: 1
        num_heads: 8
        embeddings:
            embedding_dim: 256
            scale: false
            dropout: 0.1
            norm_type: batch
            activation_type: softsign
        hidden_size: 256
        ff_size: 1024
        dropout: 0.1
